use isspace function on current character.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11791,7 +11791,6 @@ CC="$lt_save_CC"
 
 pkg_modules="gobject-2.0
 	gio-2.0
-	mee-1.0
 	gee-0.8"
 
 
@@ -14376,3 +14375,12 @@ if test -n "$ac_unrecognized_opts" && test "$enable_option_checking" != no; then
 $as_echo "$as_me: WARNING: unrecognized options: $ac_unrecognized_opts" >&2;}
 fi
 
+
+SUBMODULE_ERROR='Could not recursively update all git submodules. You may experience compilation problems if some submodules are out of date'
+SUBMODULE_OK='Git submodules updated successfully'
+if test -d .git; then \
+	   (git submodule update --init --recursive && echo $SUBMODULE_OK) \
+	|| (git submodule init && git submodule update --recursive && echo $SUBMODULE_OK) \
+	|| (git submodule init && git submodule update && echo $SUBMODULE_ERROR) \
+	|| (echo 'Git submodules could not be updated. Compilation will fail') \
+fi
